# -*- coding: utf-8 -*-
"""calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSUE1GtLiUXsj2MnVLXupASeCVs8Qonr
"""

def add(x, y):
    return x + y


def subtract(x, y):
    return x - y


def divide(x, y):
    if y == 0:
        raise ValueError("Invalid value for denominator, cant't divide by 0!")
    return x / y


def multiply(x, y):
    return x * y


def square(x):
  return x * x


def power(x, y):
    return x ** y


def sqrt(x):
    return x ** 0.5